---

# Relying on looping over hashes https://docs.ansible.com/ansible/2.4/playbooks_loops.html#looping-over-hashes
- name: add authorized keys
  authorized_key:
    user: "{{ item.value.user }}"
    state: present
    key: "{{ lookup('file', item.value.key) }}"
  with_dict: "{{ ssh.users }}"
