---
- name: Create unix groups
  group:
    name: "{{ item.1 }}"
    state: present
  with_subelements:
    - "{{ user.users|default({}) }}"
    - 'groups'

- name: Create unix users
  user:
    name: "{{ item.value.name }}"
    groups: "{{ item.value.groups|default([item.value.name]) }}"
    append: yes
    state: present
    shell: /bin/bash
    skeleton: /etc/skel
    home: "/home/{{ item.value.name }}"
    generate_ssh_key: no
  with_dict: "{{ user.users|default({}) }}"

- name: Replace bashrc for root
  template:
    src: bashrc_root.j2
    dest: /root/.bashrc
    owner: root
    group: root
    mode: 0644

- name: Replace bashrc for users
  template:
    src: bashrc.j2
    dest: "/home/{{ item.value.name }}/.bashrc"
    owner: "{{ item.value.name }}"
    group: "{{ item.value.name }}"
    mode: 0644
  with_dict: "{{ user.users|default({}) }}"


- name: Copy sudo rules
  template:
    src: "files/{{ item.1 }}"
    dest: /etc/sudoers.d/{{ item.1 }}
    owner: root
    group: root
    mode: 0400
  with_subelements:
    - "{{ user.users }}"
    - 'sudo'
    - skip_missing: true
