---
- name: Install Nginx pakacge
  apt:
    name: nginx
    state: latest
  notify:
    - start nginx

- name: Ensures include dir exists
  file:
    path: /etc/nginx/include
    state: directory

- name: copy basic config
  copy:
    src: files/general.conf
    dest: /etc/nginx/include/general.conf
    mode: 0644

- name: remove default configuration file
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - reload nginx

- name: Transfer access of www dir to Nginx user
  file:
    path: /var/www
    owner: www-data
    group: www-data
    mode: 0775
    recurse: yes

- name: create sites access log dirs
  file:
    path: "{{ item.value.log_dir }}"
    state: directory
  with_dict: "{{ nginx.sites|default({}) }}"
  when:
    - item.value.log_dir is defined

- name: add site
  template:
    src: "{{ item.value.template }}"
    dest: "/etc/nginx/sites-available/{{ item.value.domain }}.conf"
  with_dict: "{{ nginx.sites|default({}) }}"
  notify:
    - reload nginx

- name: symlink site
  file:
    path: "/etc/nginx/sites-enabled/{{ item.value.domain }}.conf"
    src: "/etc/nginx/sites-available/{{ item.value.domain }}.conf"
    state: link
  with_dict: "{{ nginx.sites|default({}) }}"
  notify:
    - reload nginx
