parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    PierreLemee\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
