parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    PierreLemee\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    PierreLemee\Twig\TwigExtension:
        class: 'PierreLemee\Twig\TwigExtension'
        arguments:
            $markdownDirectory: '%kernel.project_dir%/templates/markdown'

    ParsedownExtra:
        class: 'ParsedownExtra'


