- hosts: pierrelemee
  remote_user: root
  roles:
    - {role: system, tags: 'system'}
    - {role: user, tags: 'user'}
    - {role: ssh, tags: 'ssh'}
    - {role: static, tags: 'static'}
    - {role: fail2ban, tags: 'fail2ban'}
    - {role: htpasswd, tags: 'htpasswd'}
    - {role: php74, tags: 'php'}
    - {role: transmission, tags: 'transmission'}
    - {role: mysql80, tags: 'mysql'}
    - {role: wordpress, tags: 'wordpress'}
    - {role: ssl, tags: 'ssl'}
    - {role: nginx, tags: 'nginx'}

  vars:
    system:
      os:
        hostname: 'pitou-server'
    user:
      users:
        pitou:
          name: 'pitou'
          groups: ['pitou', 'www-data']
          sudo: ['100-pitou-nginx']
        www-data:
          name: 'www-data'
          groups: ['pitou', 'www-data']
    ssh:
      authorized_keys:
        pierre:
          file: 'pierre.pub'
          user: 'pitou'
        github:
          file: 'github.pub'
          user: 'pitou'
    static:
      pierrelemee:
        source: 'pierrelemee'
        destination: '/var/shared'
        user: 'pitou'
        group: 'pitou'
        mode: 644
      decostyl:
        source: 'decostyl'
        destination: '/var/shared'
        user: 'pitou'
        group: 'pitou'
        mode: 644
    htpassword:
      pitou:
        file: '/etc/nginx/pierrelemee.htpasswd'
        username: 'pitou'
        password: 'rdhead'
      lea:
        file: '/etc/nginx/pierrelemee.htpasswd'
        username: 'lea'
        password: '110590'

    mysql:
      root_password: '9ASnT6YYdp7DnLpD'
      databases:
        metabase:
          name: 'fabriquebienetre'
          user: 'fabriquebienetre'
          password: 'xsD3LERsKf6m96rC'
          clients: [ 'pitou' ]

    wordpress:
      version: 5.6
      sha1: 4802388640294e70820e6bf4aba681f5befa1d45
      path: '/var/www/fabriquebienetre'
      url: 'https://fabrique-du-bien-etre.com'

    ssl:
      ovh:
        app_key: 'NZWsE3rHG6EvUVSX'
        app_secret: 'bQomeYNGJyqjBHWnEZM9zOizcrkwhgix'
        consumer_key: 'd0jo9Do1pEh6TAEvvE8xqLaV8bkxG1K0'
        domains:
          - '*.pierrelemee.fr'
          - '*.deco-styl.com'
          - 'fabrique-de-bien-etre.com'
          - 'www.fabrique-de-bien-etre.com'

    nginx:
      sites:
        pierrelemee:
          domain: 'pierrelemee.fr'
          root_dir: '/var/www/pierrelemee/current/public'
          template: 'site-symfony4.j2'
          www_redirect: true
        decostyl:
          domain: 'deco-styl.com'
          root_dir: '/var/www/decostyl/current/public'
          template: 'site-symfony4.j2'
          www_redirect: true
        private:
          domain: 'private.pierrelemee.fr'
          ssl_domain: 'pierrelemee.fr'
          # To add new disks https://www.scaleway.com/en/docs/how-to-mount-and-format-a-block-volume/
          root_dir: '/media/data/transmission/downloads'
          template: 'site-static.j2'
          www_redirect: false
          htpasswd: '/etc/nginx/pierrelemee.htpasswd'
        torrent:
          domain: 'torrent.pierrelemee.fr'
          ssl_domain: 'pierrelemee.fr'
          proxy_url: 'http://127.0.0.1:9091'
          template: 'site-proxy.j2'
          www_redirect: false
          htpasswd: '/etc/nginx/pierrelemee.htpasswd'
        fabriquebienetre:
          domain: 'fabrique-de-bien-etre.com'
          ssl_domain: 'fabrique-de-bien-etre.com-0001'
          root_dir: '/var/www/fabriquebienetre'
          template: 'site-wordpress.j2'
          www_redirect: false
          htpasswd: '/etc/nginx/pierrelemee.htpasswd'
        wwwbienetre:
          domain: 'www.fabrique-de-bien-etre.com'
          redirect_domain: 'fabrique-de-bien-etre.com'
          template: 'site-redirect.j2'
          www_redirect: false
          htpasswd: '/etc/nginx/pierrelemee.htpasswd'

