---
- name: install package
  apt:
    name: fail2ban
    state: latest

- name: Config fail2ban
  template:
    src: fail2ban.conf.j2
    dest: /etc/fail2ban/jail.d/jeudemetro.conf
    mode: 0644
  notify:
    - restart fail2ban